version: '3'
services:
  app:
    build: .
    ports:
      - 8080:8080
    volumes:
      - ../:/app
    working_dir: /app
    command: /bin/sh -c "while sleep 1; do :; done"
    depends_on:
      - db 
      - redis
      - phpmyadmin
  db:
    image: mariadb:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=apps
      - MYSQL_USER=app
      - MYSQL_PASSWORD=secret_password
  redis:
    image: redis:latest
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - 8084:80
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
      - PMA_USER=app
      - PMA_PASSWORD=secret_password
    depends_on:
      - db